-- rollback: 0041_commit_sector_personas_sector_fix
-- ⚠️ 의도적으로 forward-only (executable revert 없음). 0041은 sector NOT NULL CHECK 잠복 버그를 닫는
-- corrective이므로 revert = 23514 check_violation 재도입 → 권장 안 함. 굳이 prior(buggy) 상태로 되돌리려면
-- 원 정의를 재적용: psql -f 0019_commit_sector_personas.sql (admin) + 0040_commit_sector_personas_cron.sql의
-- 최초(b3d9a88, sector 미설정) 버전 (cron). 둘 다 buggy 복원이라 운영상 무의미.
